In [ ]:
import numpy as np
print("Goolgle colab is ready")
print(np.__version__)
arr = np.array([1,2,3,4,5,6,7])
print("My first Numpy array: ", arr)
print("Array type:", type(arr))
print("Array shap:", arr.shape)
print("Array sum:", arr.sum())
print("Array average:", arr.mean())

Goolgle colab is ready
2.0.2
My first Numpy array:  [1 2 3 4 5 6 7]
Array type: <class 'numpy.ndarray'>
Array shap: (7,)
Array sum: 28
Array average: 4.0


In [ ]:
import numpy as np
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("2D Array")
print(matrix)
print("shape:", matrix.shape)
print("First row :", matrix[0])
print("First column :", matrix[:, 0])
print("Element at row 0 col 2:", matrix[0, 2])

2D Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)
First row : [1 2 3]
First column : [1 4 7]
Element at row 0 col 2: 3


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print("Original:", arr)
print("Add 10:", arr + 10)
print("multiply  by 2:", arr * 2)
print("Square each: ", arr ** 2)
print("max:", arr.max())
print("min:", arr.min())
print("sum:", arr.sum())
print("average:", arr.mean())

Original: [1 2 3 4 5 6]
Add 10: [11 12 13 14 15 16]
multiply  by 2: [ 2  4  6  8 10 12]
Square each:  [ 1  4  9 16 25 36]
max: 6
min: 1
sum: 21
average: 3.5


In [ ]:
import numpy as np
arra = np.array(46)
arr = np.array([1,2,3,4,5], ndmin=5)
matrix = np.array([[1,2,3], [4,5,6]])
matrix1 = np.array([[[[1,2,3], [4,5,6], [1,2,3], [4,5,6]]]])

print(arra.ndim)
print("The number of dimension:", arr.ndim)
print(arr.ndim)
print(matrix.ndim)
print(matrix1.ndim)

#iterating   means going through the array element one by one
arr1 = np.array([1,12,3,4,5,67,8])
for i in arr1:
  print("itereating 1 D array:", i)

arr2 = np.array([[1,2,3,4], [5,6,7,8]])
for x in arr2:
  for y in x:
    print("Itereting 2-D array:", y)

arr3 = np.array([[[1,2,3,4], [5,6,7,8], [9,10,11,12]]])
for x in arr3:
  for y in x:
    for z in y:
        print("Itereting 3-D array:", z)
#np.nditer ---- for itereting large array
for x in np.nditer(arr3):
  print(x)

#nditer

for x in np.nditer(arr2[:, ::3]):
   print(x)

#enumerate
for index, x in np.ndenumerate(arr2):
  print(index, x)

#join
join1 = np.array([1,2,3,4,5])
join2 = np.array([9,8,7])

join_final = np.concatenate((join1, join2))
print(join_final)


join3 = np.array([[1,2,3], [4, 6, 5]])
join4 = np.array([[9,8,7], [0, 11, 12]])

join = np.concatenate((join3, join4), axis = 1)
print(join)

#stack
print("Stack functions")
stack = np.stack((join3, join4), axis = 1)
stack1 = np.hstack((join3, join4))
stack2 = np.vstack((join3, join4))
stack3 = np.dstack((join3, join4))
print("Stack")

print(stack)
print("Stack1")

print(stack1)
print("Stack2")

print(stack2)
print("Stack3")

print(stack3)

#split
split = np.array([1,12,3,4,5,67,8])
new_split = np.array_split(split, 3)
print("slipting 1 D")
print(new_split)

arr_split = np.array([[9,8,7], [0, 11, 12],[1,2,3]])
#new_arr_split = np.array_split(split, 3)
new_arr_split = np.array_split(arr_split, 3, axis =1)
new_arr_split_v = np.vsplit(arr_split, 3)
new_arr_split_h = np.hsplit(arr_split, 3)
new_arr_split = np.vsplit(arr_split, 3)


print("spilting 2 D")
print(new_arr_split)
print("vspilt")
print(new_arr_split_v)
print("hspilt")
print(new_arr_split_h)

#search
#where() ---it get the specific index of the array element where the condition is meant
arr_src = np.array([1,2,3,4,5,5])
src = np.where(arr_src == 1)
print(src)

#searchsort() --- it get the specific index where the element you want to insert in the array  inoder of ascending order
sort = np.searchsorted(arr_src, [2,3,4])
sort1 = np.searchsorted(arr_src, 9, side ='right')

print("search sorted")
print(sort)










0
The number of dimension: 5
5
2
4
itereating 1 D array: 1
itereating 1 D array: 12
itereating 1 D array: 3
itereating 1 D array: 4
itereating 1 D array: 5
itereating 1 D array: 67
itereating 1 D array: 8
Itereting 2-D array: 1
Itereting 2-D array: 2
Itereting 2-D array: 3
Itereting 2-D array: 4
Itereting 2-D array: 5
Itereting 2-D array: 6
Itereting 2-D array: 7
Itereting 2-D array: 8
Itereting 3-D array: 1
Itereting 3-D array: 2
Itereting 3-D array: 3
Itereting 3-D array: 4
Itereting 3-D array: 5
Itereting 3-D array: 6
Itereting 3-D array: 7
Itereting 3-D array: 8
Itereting 3-D array: 9
Itereting 3-D array: 10
Itereting 3-D array: 11
Itereting 3-D array: 12
1
2
3
4
5
6
7
8
9
10
11
12
1
4
5
8
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
[1 2 3 4 5 9 8 7]
[[ 1  2  3  9  8  7]
 [ 4  6  5  0 11 12]]
Stack functions
Stack
[[[ 1  2  3]
  [ 9  8  7]]

 [[ 4  6  5]
  [ 0 11 12]]]
Stack1
[[ 1  2  3  9  8  7]
 [ 4  6  5  0 11 12]]
Stack2
[[ 1  2  3]
 [ 4  6  5]
 [ 9 

In [ ]:
#random
from numpy import random
ran = random.randint(10)
ran1 =random.rand()
ran2 = random.randint(100, size = 5 )
ran3 = random.rand(5)
ran4 = random.randint(50, size = (4,5))
#choice
ran5 = random.choice([3,4,5,6,7,8,898])
ran5 = random.choice([3,4,5,6,7,8,898], size = (2,2,3))




print(ran)
print(ran1)
print(ran2)
print(ran3)
print(ran4)
print(ran5)


9
0.9821068105582744
[28  9 98 73 51]
[0.18622335 0.15619683 0.61083144 0.06915682 0.64750927]
[[31 40 15 24  8]
 [21 45 13 18 25]
 [46 20  9  8 42]
 [22  9 37 10 47]]
[[[  7   3   4]
  [  7 898   5]]

 [[  7   7 898]
  [  5   8   6]]]


In [ ]:
#Arithemetic
import numpy as np
arr = np.array([10,12,11,2,6,3,4])
arr1 = np.array([10,12,11,2,6,3,4])
#addition
addarr =np.add(arr, arr1)
#substraction
subarr =np.subtract(arr, arr1)
mularr =np.multiply(arr, arr1)
modarr =np.mod(arr, arr1)
divmodarr =np.divmod(arr, arr1)

print("addtion:", addarr)
print("substraction:", subarr)
print("Multiplication:", mularr)
print("Remainder:", modarr)
print("quient and remainder:", divmodarr)

#rounding
round = np.array([3.224, -4.54])
truc_round= np.trunc(round)
fix = np.fix(round)
floor = np.floor(round)
round1 = np.round(round)
ceil = np.ceil(round)
print("truc",truc_round)
print("fix:", fix)
print("floor:", floor)
print("Round:", round)
print("ceil:", ceil)

#log
arrlog = np.array([1,10,100,100])
print('Natiral log:', np.log(arrlog))
print("log base 2:", np.log2(arrlog))
print("log base 10:", np.log10(arrlog))















addtion: [20 24 22  4 12  6  8]
substraction: [0 0 0 0 0 0 0]
Multiplication: [100 144 121   4  36   9  16]
Remainder: [0 0 0 0 0 0 0]
quient and remainder: (array([1, 1, 1, 1, 1, 1, 1]), array([0, 0, 0, 0, 0, 0, 0]))
truc [ 3. -4.]
fix: [ 3. -4.]
floor: [ 3. -5.]
Round: [ 3.224 -4.54 ]
ceil: [ 4. -4.]
Natiral log: [0.         2.30258509 4.60517019 4.60517019]
log base 2: [0.         3.32192809 6.64385619 6.64385619]
log base 10: [0. 1. 2. 2.]
